name: Check Markdown links

on: [pull_request]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Link Checker
        uses: lycheeverse/lychee-action@master
        with:
          #fail: true
          args: --verbose --no-progress './website/**/*.md' --accept 429
