name: Check Markdown links

on:
  schedule:
    - cron: '45 15 * * 2'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Link Checker
        uses: lycheeverse/lychee-action@master
        with:
          args: --verbose --no-progress './website/**/*.md' --accept 429
